### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tune6688** [reneeb/otrs-CIBarcode#3]
Dear Reneeb
Sorry to bother you . My system is centos7 and Znuny version is 6.034.  I have installed the module GD::Barcode v1.15, when I install this plug-in  also show below  error message. I don't konw what to do ,can you give me some suggestions?
Thanks for your help!

An Error Occurred

Sorry, can't install package, because module GD::Barcode v1.15 is required and not installed!

Error Details

Backend ERROR: OTRS-CGI-93 Perl: 5.16.3 OS: linux Time: Fri Jun 4 01:56:45 2021

 Message: Sorry, can't install package, because module GD::Barcode v1.15 is required and not installed!

 RemoteAddress: ::1
 RequestURI: /otrs/index.pl

 Traceback (5131): 
   Module: Kernel::System::Package::_CheckModuleRequired Line: 3994
   Module: Kernel::System::Package::PackageInstall Line: 552
   Module: Kernel::Modules::AdminPackageManager::_InstallHandling Line: 2193
   Module: Kernel::Modules::AdminPackageManager::Run Line: 1305
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 1136
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 39
   Module: (eval) (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 207
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 173
   Module: ModPerl::Registry::handler (v1.99) Line: 32"

**Comment by reneeb** [comment]
How did you install the module? What's the output for `perl -MGD::Barcode\ 9999 -e 1`? What's the output for `su -c 'perl -MGD::Barcode\ 9999 -e 1' <user _for_webserver>`?

**Comment by tune6688** [comment]
Thanks your quick reply. I used "cpan GD::Barcode " to install the module.
[root@localhost ~]# cpan GD::Barcode 
Reading '/root/.cpan/Metadata'
Database was generated on Fri, 04 Jun 2021 04:17:03 GMT
Running install for module 'GD::Barcode'
Running make for K/KW/KWITKNR/GD-Barcode-1.15.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/K/KW/KWITKNR/GD-Barcode-1.15.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/K/KW/KWITKNR/CHECKSUMS
Checksum for /root/.cpan/sources/authors/id/K/KW/KWITKNR/GD-Barcode-1.15.tar.gz ok
CPAN.pm: Building K/KW/KWITKNR/GD-Barcode-1.15.tar.gz

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for GD::Barcode
....
Appending installation info to /root/perl5/lib/perl5/x86_64-linux-thread-multi/perllocal.pod
  KWITKNR/GD-Barcode-1.15.tar.gz
  /usr/bin/make install  -- OK

[root@localhost ~]# perl -MGD::Barcode\ 9999 -e 1
GD::Barcode version 9999 required--this is only version 1.15.
BEGIN failed--compilation aborted.

**Comment by tune6688** [comment]
Dear Reneeb
I also used "cpanm GD::Barcode and perl -MCPAN -e shell install GD::Barcode",but the same issue.
Could you give me some guidance. Thank you so much!

**Comment by tune6688** [comment]
Thank you for your great help !
I installed it successfully!
Here is what I did:"wget http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-GD-Barcode-1.15-15.el7.noarch.rpm
yum install perl-GD-Barcode-1.15-15.el7.noarch.rpm -y"
